## **Importing libraries**

In [31]:
import numpy as np
import matplotlib.pyplot as plt  # For graph
import pandas as pd

## **Importing dataset and divide in independent variable x and dependent variable y**

In [32]:
from google.colab import files
uploaded = files.upload()
dataset = pd.read_csv('insurance.csv')
x = dataset.iloc[:, [0,1,5]].values
y = dataset.iloc[:, -1].values

print("X dataset: \n\n", x)
print("Y dataset: \n\n", y)


Saving insurance.csv to insurance (1).csv
X dataset: 

 [[19 'female' 'southwest']
 [18 'male' 'southeast']
 [28 'male' 'southeast']
 ...
 [18 'female' 'southeast']
 [21 'female' 'southwest']
 [61 'female' 'northwest']]
Y dataset: 

 [16884.924   1725.5523  4449.462  ...  1629.8335  2007.945  29141.3603]


## **There is no missing data found in the dataset.**

## **Encoding for categorical data for independent variable**

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [1,2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [36]:
print(x)

[[1.0 0.0 1.0 ... 0.0 1.0 19]
 [0.0 1.0 1.0 ... 1.0 0.0 18]
 [0.0 1.0 1.0 ... 1.0 0.0 28]
 ...
 [1.0 0.0 1.0 ... 1.0 0.0 18]
 [1.0 0.0 1.0 ... 0.0 1.0 21]
 [1.0 0.0 1.0 ... 0.0 0.0 61]]


## **Spliting the dataset in Training set and testing set**

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 2)

In [38]:
print(x_train)

[[1.0 0.0 1.0 ... 0.0 1.0 29]
 [0.0 1.0 0.0 ... 0.0 0.0 32]
 [1.0 0.0 1.0 ... 1.0 0.0 44]
 ...
 [0.0 1.0 1.0 ... 0.0 1.0 61]
 [1.0 0.0 1.0 ... 0.0 1.0 51]
 [1.0 0.0 0.0 ... 0.0 0.0 58]]


In [39]:
print(x_test)

[[0.0 1.0 0.0 ... 0.0 0.0 23]
 [1.0 0.0 0.0 ... 0.0 0.0 55]
 [0.0 1.0 0.0 ... 0.0 0.0 50]
 ...
 [0.0 1.0 1.0 ... 0.0 1.0 35]
 [0.0 1.0 1.0 ... 0.0 0.0 59]
 [1.0 0.0 1.0 ... 0.0 1.0 25]]


In [40]:
print(y_train)

[ 4529.477     4667.60765  48885.13561   5354.07465   8582.3023
  2842.76075  28950.4692    1711.0268    4428.88785   8733.22925
  3500.6123    4561.1885   24671.66334  14319.031     1242.26
  4746.344    46130.5265   44202.6536   36898.73308  15359.1045
 30166.61817  16796.41194  14988.432    11082.5772    7050.0213
  8527.532    21223.6758   37079.372    37165.1638   23807.2406
  2134.9015    9748.9106   12231.6136    6500.2359    1261.859
  5708.867     1137.4697   47305.305     1759.338     7228.21565
  8604.48365  23401.30575   4435.0942    3994.1778    1737.376
  9222.4026    7650.77375  20878.78443   9869.8102    7337.748
  1628.4709   18608.262     9541.69555   4438.2634   33307.5508
 11735.87905  13887.204     9500.57305   5116.5004   36397.576
 34439.8559    3935.1799   10072.05505   8083.9198   11552.904
  8932.084    14449.8544    4357.04365   4441.21315   6184.2994
  7518.02535  12829.4551    1704.5681    3757.8448    4466.6214
 27218.43725   7740.337    35069.37452   1708

In [41]:
print(y_test)

[ 2395.17155 11286.5387   9617.66245  1719.4363   8891.1395   5662.225
 12609.88702  2196.4732  14254.6082   7209.4918  12222.8983   2219.4451
 19444.2658   1121.8739  26392.26029 12925.886    3645.0894   5327.40025
 18972.495    2203.47185 11840.77505  2597.779   40182.246   22331.5668
 37484.4493  10577.087    3206.49135  8944.1151   3577.999    3176.8159
  5397.6167   3956.07145  4931.647    4239.89265 14478.33015  1631.6683
 38792.6856  20420.60465 35147.52848 27000.98473  2117.33885 34472.841
  7419.4779   2007.945    6781.3542   5375.038   10264.4421   3471.4096
  4266.1658  20630.28351  4915.05985  1242.816   17748.5062  43921.1837
  6496.886   11538.421    1969.614    7160.3303   2154.361   40273.6455
 14349.8544   2103.08     2850.68375 42560.4304   1241.565   11944.59435
 21797.0004   1880.07    13457.9608   7443.64305 10704.47    36580.28216
 30284.64294  6571.544   12741.16745  9872.701    2020.177    1909.52745
  2498.4144  12622.1795  10791.96     9964.06     1163.4627  1